### ISSUE TITLE
Uncaught TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by Damonwu1988** [lizhonghui/angular2-demo#1]
按照原项目代码，npm start 执行后在浏览器访问报Uncaught TypeError: Object.assign is not a function 错误，这可以怎样解决？

**Comment by lizhonghui** [comment]
是在IE下跑的这个应用么？如果是的话可以在main.js里加上如下内容：
```
// 在 import 'zone.js'; 下面加
import 'core-js';
```
试试看

**Comment by Damonwu1988** [comment]
我在chrome下面打开的，按你的建议改后。报了Unhandled promise rejection Error: Angular requires Zone.js prolyfill.这个错了。:Object.assign is not a function，应该是es6语法没有编译到吧？

**Comment by lizhonghui** [comment]
试试改成这样：
```
import 'core-js';
import 'zone.js';

// JiT启动模式
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by Damonwu1988** [comment]
ERROR in ./main.ts
Module not found: Error: Can't resolve 'core.js' in 'E:\Angular\angular2-demo-ma
ster'
直接引入编译就不通过了，但实际上是有core库的

**Comment by Damonwu1988** [comment]
搞定，这样就可以了，这是什么原因呢？

**Comment by lizhonghui** [comment]
`import zone.js` 这个是必不可少得polyfill，跟变化检测相关的
`import 'core-js'` 包含es6/7等特性的polyfill，在高级浏览器里运行可以不用引入，如果想支持更多低端浏览器的话需要引入。你的chrome报错确实很奇怪，可能是你的chrome版本太低了

**Comment by Damonwu1988** [comment]
了解了，应该是跟chrome版本有关系，谢谢帮忙解决问题。

**Comment by Damonwu1988** [comment]
不知道你在慕课网上讲课的ppt能够分享下？

发自我的 iPhone

**Comment by lizhonghui** [comment]
https://github.com/lizhonghui/angular2-demo/blob/master/assets/Angular2-Overview.pptx

**Comment by Damonwu1988** [comment]
想问下在angular应用里的页面跳转有多少种方式，是否一定能要使用路由的？

**Comment by lizhonghui** [comment]
why not!
不用router可以参考这个：https://medium.com/@tudorgergely/injecting-components-dynamically-in-angular-2-3d36594d49a0

**Comment by Damonwu1988** [comment]
ERROR TypeError: Cannot read property 'ngAfterViewChecked' of undefined

**Comment by Damonwu1988** [comment]
ERROR TypeError: Cannot read property 'ngAfterViewChecked' of undefined,想请教下报了这个错可以怎样解决？

**Comment by lizhonghui** [comment]
有更多上下文信息？代码贴一下？

**Comment by Damonwu1988** [comment]
这边删掉后重新install 模块库就可以了！想问下angular2使用 webpack自定义配置打包还是 angular cli 配置打包好？

发自我的 iPhone

**Comment by lizhonghui** [comment]
这个Demo是去年做的，比较老了。
现在angular-cli的功能已经非常稳定而且强大了，cli的构建本身就是基于webpack，有一套比较完善的分环境webpack构建流程，墙裂推荐。
只有一些个别情况考虑webpack构建（可使用`ng eject`命令将CLI的webpack配置释放出来），例如需要加入自定义的plugin或loader等，如最近火起来的prepack，或者希望通过进一步优化提升构建速度（CLI的构建速度是有点慢）

**Comment by Damonwu1988** [comment]
angular cli确实是很方便，感觉非常适合不是很懂webpack的初学者。

**Comment by lizhonghui** [comment]
恩，webpack也可以多了解，非常好用的的bundle工具。理解了webpack对CLI的构建理解也会加深
